### PR TITLE
Fixing calc_dbz and tests scripts and functions

### PR DESCRIPTION
**Pull request by MathildeDupouy**
This branch is the fusion of two branches that have been used to test the method to calculate the field shift. 

The implementation has thus been modified :
- Correction of the undefined value at the zero frequency ;
- A padding is made to enhance the estimation result. A default padding is suggested and the user also has te possibility to choose one ;
- FT linearity is used to reduce the execution time ;

Moreover, the scripts for the tests and figures of results are kept in a folder.

Finally, a function to down sample a 3D matrix has been made for future tests with modified resolutions.

### CODE REVIEW

**Comment by evaalonsoortiz** [comment]
@MathildeDupouy  
In line 199 of test_calcBdz.m, "anal" is not defined. Is this a typo?
https://github.com/evaalonsoortiz/Fourier-based-field-estimation/blob/ec1b9c9a20d6e26747b26ecf10fc681033fb8718/tests_calc_dbz/test_calcBdz.m#L199

**Comment by evaalonsoortiz** [comment]
@MathildeDupouy When running "test_bufferZubal.m" I obtain the following error: 


`Error using fftn`
`FFTN output size must have at least NDIMS elements.`

`Error in FBFest/calc_dBz (line 66)`
            `FT_chi = fftn(obj.sus - obj.sus_ext, obj.dim_with_buffer); % region of interest`

`Error in FBFest (line 39)`
            `obj.calc_dBz();`

`Error in test_bufferZubal (line 84)`
    `dBz_obj = FBFest('Zubal', sus, zubal_sus_dist.image_res, dim_without_buffer, sus_ext, b0, [256, 256, 128]);`

Should I be able to run this script without making any changes to the parameters (such as a the matrix dimensions)?

**Comment by MathildeDupouy** [comment]
@evaalonsoortiz I am going to check the error. 
Yes the variable "anal" stands for analytical, a matrix I had previously store to run some new tests for my paper. I thought I hadn't push it, I am going to correct that.

**Comment by evaalonsoortiz** [comment]
Based on what is in the readme, I have also tried to run the following to test the cylindrical model:

`cylindrical_sus_dist = Cylindrical( [256 256 256], [1 1 1], 5, 0, [0 3.6e-6]);`
`cylindrical_dBz = FBFest( cylindrical_sus_dist.volume, [1 1 1], [256 256 256] );`

However, it looks like the input parameters for FBFest have changed, can you update the readme to reflect that?

**Comment by evaalonsoortiz** [comment]
Another test:

I tried running test_resZubal.m and obtained the following error:

`Index exceeds the number of array elements (1).`

`Error in sub_sample_3D (line 52)`
`vol_lowRes = vol_filt(phase(1):factor(1):end, phase(2):factor(2):end, phase(3):factor(3):end);`

`Error in test_resZubal (line 138)`
`zubal_filt = sub_sample_3D(zubal_sus_dist.volume, 2);`

**Comment by MathildeDupouy** [comment]
I will open a new pull request with the new commit to fix all the issues we've discussed because I don't know how to ammend this one. I have tested all the scripts this time, my bad.

**Comment by MathildeDupouy** [comment]
I made the appropriate corrections. Is it now working ?

**Comment by evaalonsoortiz** [comment]
Test results:

- test_calcBdz.m : ran with no errors
- test_bufferZubal.m : same error as posted above (FFTN must have at least NDIMS elements)
- test_resZubal.m : ran with no errors

I also tried the following:

`cylindrical_sus_dist = Cylindrical( [256 256 256], [1 1 1], 5, 0, [0 3.6e-6]);`
`cylindrical_dBz = FBFest( 'spherical', cylindrical_sus_dist.volume, [1 1 1], [256 256 256], 3.6e-6);`

Which resulted in the this message:
`Error using repmat
Requested 2048x2048x2048 (64.0GB) array exceeds maximum array size preference. Creation of
arrays greater than this limit may take a long time and cause MATLAB to become unresponsive.
See array size limit or preference panel for more information.`

Did you test the above with a 256^3 matrix, and if so, is this the expected padded array size?

**Comment by evaalonsoortiz** [comment]
I have a suggestion; for the sample code lines given in the README, perhaps you could write one with parameters that have been tested (the matrix size and resolution), for each phantom type? 

For example, in the README write:
`cylindrical_sus_dist = Cylindrical( [256 256 256], [1 1 1], 5, 0, [0 3.6e-6]);`
`cylindrical_dBz = FBFest( 'spherical', cylindrical_sus_dist.volume, [1 1 1], [256 256 256], 3.6e-6);`

if you know that [256 256 256], [1 1 1], etc. are parameter combinations that run successfully. This way the person testing the code won't run into edge cases where errors are produced.

**Pull request merged**
